export const accordionData = [
    { "id": "rec5Uh56048pvXZV5",
    "createdTime": "2023-05-23T18:26:38.000Z",
    "fields": 
        { "Namn": "Manhattan", 
        "Taggar": ["Murrig", "Klassisk", "Spritig"], 
        "Bassprit": "Whisky", 
        "Tillredning": 
        "Rör ingredienserna kalla i ett rörglas med is. \nSila upp i ett kylt cocktailglas. \nGarnera med ett inlagt körsbär.\n", "Kommentar": "The Manhattan was the most famous cocktail in the world shortly after it was invented in New York City’s Manhattan Club, some time around 1880 (as the story goes).", "Ingredienser": "4 cl Bourbon eller rye\n2 cl Söt Vermouth \n5 droppar Bitters \n\n" } }, { "id": "recGQWBvP1rboYPKM", "createdTime": "2023-05-23T17:51:27.000Z", "fields": {} }, { "id": "recPVN6GQ9aNVFo03", "createdTime": "2023-05-23T17:51:27.000Z", "fields": {} }, { "id": "recSM0wYZr8DWUVuR", "createdTime": "2023-05-23T18:28:30.000Z", "fields": { "Namn": "Scofflaw", "Taggar": ["Klassisk"], "Bassprit": "Whisky", "Tillredning": "Skakas med is. \n\n", "Kommentar": "Scofflaw debuterade på legendariska Harry’s Bar i Paris 1924. Namnet kommer från det man brukade kalla de som drack olagligt under förbudstiden i USA, alltså omkring den tid drinken skapades.\n\nLättdrucken", "Ingredienser": "4,5 cl Rye whiskey\n3 cl torr vermouth\n2 cl limejuice\n1,5 cl grenadin\nTvå droppar apelsinbitter\n" } }, { "id": "recVyi3uwgThXL3wh", "createdTime": "2023-05-23T18:15:18.000Z", "fields": { "Namn": "Whisky Sour", "Taggar": ["Klassisk", "Skummig"], "Bassprit": "Whisky", "Tillredning": "Skaka ingredienserna luftiga utan is och tillsätt till sist is för att skaka drinken kall. Dubbelsila upp i glaset \n", "Ingredienser": "5 cl Whiskey \n3 cl Citronjuice \n2 cl Sockerlag \nEn äggvita \n" } }, { "id": "recXdMNHpm93BEKSZ", "createdTime": "2023-05-23T17:51:27.000Z", "fields": {} }, { "id": "recZEA2tNgKCa9kin", "createdTime": "2023-05-23T18:16:16.000Z", "fields": { "Namn": "New York Sour ", "Taggar": ["Klassisk", "Skummig"], "Bassprit": "Whisky", "Tillredning": "Använd ett lågt glas med is. Skaka ingredienserna luftiga utan is och tillsätt till sist is för att skaka drinken kall. \nSila upp i glaset och toppa med rött vin.\n", "Ingredienser": "5 cl Whiskey \n3 cl Citronjuice \n2 cl Sockerlag \nEn äggvita \nToppa med rött vin (2 cl)\n" } }, { "id": "recpWXrii915F4ss6", "createdTime": "2023-05-23T18:25:20.000Z", "fields": { "Namn": "New York Cocktail", "Taggar": ["Fräsch", "Klassisk"], "Bassprit": "Whisky", "Tillredning": "Skaka drinken kall med is och dubbelsila upp i ett frostat glas på fot.\n", "Ingredienser": "5 cl Rye Whiskey \n3 cl Limejuice \n2 cl Grenadin/Granatäppelsocker \n" } }
];